### ISSUE TITLE
libnfporb update

### ISSUE THREAD

**Issue by kallaballa** [martinhansdk/Flatpack#1]
I'd like to bring to your attention that I've finally put the necessary work into libnfporb to make it robust. There are still issues remaining: https://github.com/kallaballa/libnfporb/issues but they are rare and not critical. Also floating-point and arbitrary precision both yield the same result in the test though that parity might break with a mix of very small and very large geometries.

**Comment by martinhansdk** [comment]
Thank you for this heads up. I have decided not to use libnrfporb to implement nesting in this project.

**Comment by kallaballa** [comment]
Good decision. There are better alternatives by now.
